apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shop-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: shop-operator
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: shop-operator
  template:
    metadata:
      labels:
        app: shop-operator
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: operator
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
