apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shop-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "shop-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "shop-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "shop-operator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: operator
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        args:
        - --shop-base-domain={{ .Values.shopBaseDomain }}
        - --rpc-url={{ .Values.chain.rpcUrl }}
        - --chain-id={{ .Values.chain.id }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10