{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.serviceAccount.name }}-role
  labels:
    {{- include "shop-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets", "services"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["shop.shophub.local"]
    resources: ["shops", "discordchannels", "wallets"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["shop.shophub.local"]
    resources: ["shops/status", "discordchannels/status", "wallets/status"]
    verbs: ["get", "patch", "update"]
  - apiGroups: ["shop.shophub.local"]
    resources: ["shops/finalizers", "discordchannels/finalizers", "wallets/finalizers"]
    verbs: ["update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.serviceAccount.name }}-rolebinding
  labels:
    {{- include "shop-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.serviceAccount.name }}-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
{{- end }}