apiVersion: v1
kind: Service
metadata:
  name: {{ include "shop-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "shop-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "shop-operator.selectorLabels" . | nindent 4 }}