apiVersion: v2
name: shop-operator
description: Helm chart for deploying shop-operator and installing CRDs
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - shop
  - operator
  - kubernetes
maintainers:
  - name: Nemanja Simsic
  - name: Katarina Spremic