apiVersion: v2
name: shop-operator
description: Helm chart for deploying shop-operator and installing CRDs
type: application
version: 0.2.0
appVersion: "0.2.0"
keywords:
  - shop
  - operator
  - kubernetes
maintainers:
  - name: slepimis120
    url: https://github.com/slepimis120
  - name: s-katarina
    url: https://github.com/s-katarina
