apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shophub.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "shophub.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "shophub.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "shophub.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: shophub
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 12 }}