apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shop.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: shop
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "shop.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "shop.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: shop
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
