apiVersion: v2
name: anvil
description: Anvil (Foundry) razvojni EVM lanac na kojem prodavnice naplacuju
type: application
version: 1.0.0
appVersion: "latest"
keywords:
  - anvil
  - foundry
  - ethereum
  - testnet
maintainers:
  - name: slepimis120
    url: https://github.com/slepimis120
  - name: s-katarina
    url: https://github.com/s-katarina
